BasicFBGraphApi/BasicFBGraphApi/Models/ErrorViewModel.cs
namespace BasicFBGraphApi.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BasicFBGraphApi/BasicFBGraphApi/Models/FacebookData.cs
namespace BasicFBGraphApi.Models
{
    public class FacebookData
    {
        public string id { get; set; } = null;
        public string email { get; set; } = null;
        public string first_name { get; set; } = null;
        public string last_name { get; set; } = null;
        public string name_format { get; set; } = null;
        public string name { get; set; } = null;
        public string accounts { get; set; } = null;
        public string token { get; set; }

        #region FaceBookPage
        public string igName { get; set; } = null;
        public string igId { get; set; } = null;
        public string about { get; set; } = null;
        public string birthday { get; set; } = null;
        public string category { get; set; } = null;
        public bool is_always_open { get; set; }
        public long followers_count { get; set; }
        public string instagram_business_account { get; set; } = null;
        public string link { get; set; } = null;
        public string name_with_location_descriptor { get; set; } = null;
        #endregion FaceBookPage
    }
}

BasicFBGraphApi/BasicFBGraphApi/Models/InstagramData.cs
namespace BasicFBGraphApi.Models
{
    public class InstagramData
    {
        public string name { get; set; } = null;
        public string about { get; set; } = null;
        public string birthday { get; set; } = null;
        public string category { get; set; } = null;
        public string is_always_open { get; set; } = null;
        public string followers_count { get; set; } = null;
        public string instagram_business_account { get; set; } = null;
        public string link { get; set; } = null;
        public string name_with_location_descriptor { get; set; } = null;
    }
}

BasicFBGraphApi/BasicFBGraphApi/Controllers/FBGraphController.cs
using BasicFBGraphApi.GraphService;
using BasicFBGraphApi.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace BasicFBGraphApi.Controllers
{
    public class FBGraphController : Controller
    {
        private readonly IGraphApi _graphApi;
        public static FacebookData model = new FacebookData();

        public FBGraphController(IGraphApi graphApi)
        {
            _graphApi = graphApi;
        }

        public IActionResult Index()
        {
            return View(model);
        }

        [HttpPost]
        public IActionResult Index(string token)
        {
            model = _graphApi.GetProperties(token);
            return RedirectToAction("Index");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BasicFBGraphApi/BasicFBGraphApi/Views/FBGraph/Index.cshtml
@model FacebookData


<div class="text-center">
    <form asp-controller="FBGraph" asp-action="Index" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="card-body">
                <div class="form-group row mb-2">
                    <label class="col-form-label col-sm-3">Your Token :</label>
                    <div class="col-sm-9">
                        <input type="text" asp-for="token" class="form-control" />
                    </div>
                </div>
            </div>
            <div class="form-group row mb-2">
                <div class="col-sm-9">
                    <button type="submit" class="btn btn-primary">Send Token</button>
                </div>
            </div>
        </div>
    </form>
</div>

&nbsp;
<div class="container">
    <div class="row">
        <div class="col-6">
            <label>Proporties :</label>
        </div>
        <div class="col-6">
            <label>Your Profile :</label>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul>
                <li>First Name : </li>
                <li>Last Name  : </li>
                <li>Email      : </li>
                <li>Id         : </li>
                <li>Name Format: </li>
                <li>Name       : </li>
                <li>Accounts   : </li>
            </ul>
        </div>
        <div class="col-6">
            <ul>
                <li>@Model.first_name</li>
                <li>@Model.last_name</li>
                <li>@Model.email</li>
                <li>@Model.id</li>
                <li>@Model.name_format</li>
                <li>@Model.name</li>
                <li>@Model.accounts</li>
            </ul>
        </div>
    </div>
    <div class="row">
        <div class="col-6">
            <ul>
                <li>Instagram Name                : </li>
                <li>Instagram Id                  : </li>
                <li>About                         : </li>
                <li>Birthday                      : </li>
                <li>Category                      : </li>
                <li>Is Always Open?               : </li>
                <li>Followers Count               : </li>
                <li>Business Account              : </li>
                <li>Link                          : </li>
                <li>Name With Location Descriptor : </li>
            </ul>
        </div>
        <div class="col-6">
            <ul>
                <li>@Model.igName</li>
                <li>@Model.igId</li>
                <li>@Model.about</li>
                <li>@Model.birthday</li>
                <li>@Model.category</li>
                <li>@Model.is_always_open</li>
                <li>@Model.followers_count</li>
                <li>@Model.instagram_business_account</li>
                <li>@Model.link</li>
                <li>@Model.name_with_location_descriptor</li>
            </ul>
        </div>
    </div>
</div>

BasicFBGraphApi/BasicFBGraphApi/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasicFBGraphApi</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasicFBGraphApi.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>